### PR TITLE
Use common loading view instead of standard progress bar

### PR DESCRIPTION
**Pull request by BismeetSingh**
Replaced progress bar with the lottie animated view. #9

### CODE REVIEW

**Comment by cdhiraj40** [comment]
Hey, @BismeetSingh can you maybe add a screen recording for me to see?

**Comment by BismeetSingh** [comment]
https://user-images.githubusercontent.com/13601266/193454792-6ff2f34c-db7e-46b2-9a0c-612757f7fe62.mp4

**Review by cdhiraj40 — APPROVED** [review]

**Comment by cdhiraj40** [comment]
@BismeetSingh Thanks for your PR, everything looks fine! Merging :tada:

**Comment by BismeetSingh** [comment]
I think the build failure is a part of another issue ?

**Pull request merged**
