### PR TITLE
Added internet network connection alert dialogue box

### LINKED ISSUE #15: Handling internet failure while fetching data
**Is your feature request related to a problem? Please describe.**
LeetDroid fetches various types of data like questions which requires an active internet connection. There is no concrete implementation in the app to handle an internet failure while the internet is getting fetched.

**Describe the solution you'd like**
We should show a snack bar if there is no internet connection while fetching the data.

**Additional context**
You can check out #12 by @BismeetSingh for the implementation of this in the recent submissions screen.

Feel free to take different screens, implement the feature and create a PR.
 1. [General Discussion Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/discussion/GeneralDiscussionFragment.kt)
 2.  [Contributors Fragment ](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/preferences/ContributorsFragment.kt)
 3. [Question Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/question/QuestionFragment.kt)
 4. [Question Discussion Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/question/QuestionDiscussionFragment.kt)
 5. [Question Solution Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/question/QuestionSolutionFragment.kt)
 6. [Contest Details Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/user/ContestDetailsFragment.kt)
 7. [My Profile Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/user/MyProfileFragment.kt)
 8. [All Questions Fragment](https://github.com/cdhiraj40/LeetDroid/blob/development/app/src/main/java/com/cdhiraj40/leetdroid/ui/fragments/AllQuestionsFragment.kt)

### PR DESCRIPTION
**Pull request by mksiddiq**
# Description
Added internet network connection alert dialogue box in the Contributors Fragment.

Fixes #15 

internet check feature LeetDroid

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by mksiddiq** [comment]
@cdhiraj40 do check it out and let me know :D

**Comment by cdhiraj40** [comment]
You should do one of the following: 
1. We should not show a dialog, but maybe show a snack bar with action for open settings to turn on the internet.
2. Show a no internet error view just like this emoji ⚠️ and have a button below that view to open settings to turn on the internet

**Comment by mksiddiq** [comment]
@cdhiraj40 got it, working on it.

**Comment by mksiddiq** [comment]
Hey @cdhiraj40 I changed it to a snackbar :D 
snackbar internet LeetDroid
do let me know if it is fine :)
Also, the this repo is hacktoberfest accepted right?

**Comment by mksiddiq** [comment]
@cdhiraj40 Today is the last day of Hacktoberfest. It is my request to please review the PR as I have done all the changes. Hope you understand, it is very important for me. Thank you :D

**Review by cdhiraj40 — APPROVED** [review]
LGTM 🚀 
Thanks for your contribution 🎉 

Also hey @mksiddiq ! we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. 
Join our community: https://bit.ly/cerritus-coders

**Comment by mksiddiq** [comment]
@cdhiraj40 Thank you so much for approving the PR! :D The event that you have mentioned.... it is only till 31 october it seems...  which is today :(

**Comment by cdhiraj40** [comment]
> @cdhiraj40 Thank you so much for approving the PR! :D The event that you have mentioned.... it is only till 31 october it seems... which is today :(

you have contributed to the projects mentioned in the event so you can still register and earn swags as long as you are from India 😅

**Comment by mksiddiq** [comment]
> > @cdhiraj40 Thank you so much for approving the PR! :D The event that you have mentioned.... it is only till 31 october it seems... which is today :(
> 
> you have contributed to the projects mentioned in the event so you can still register and earn swags as long as you are from India 😅

Oh nice! I am from India. Registration done :D

**Pull request merged**
