### PR TITLE
Fix/handle internet failure

### LINKED ISSUE #5: handling internet connection
**Is your feature request related to a problem? Please describe.**
Currently, a user needs an active internet connection for using an app. There should be proper checks for internet connection.  

**Describe the solution you'd like**
Checking if there is an active connection is more than enough. It might be a big change as it has not been implemented yet and this change has to be done throughout the app. A proper solution I can think of is implementing this to one-one screens and making PR for it.  

**Describe alternatives you've considered**
None

### PR DESCRIPTION
**Pull request by BismeetSingh**
# Description

Added live data to keep tracking of lost internet connection. Wired it into main activity currently, can also use for other activities.

Fixes #5 

## Screen recording

https://user-images.githubusercontent.com/13601266/194358540-b15c7660-7d56-45ab-9fb1-49fb87478ce1.mp4

### CODE REVIEW

**Comment by cdhiraj40** [comment]
Hey @BismeetSingh this is really great! I believe we should the show snack bar only when a user tries to reload rather than when they turn on the internet.

### Flow:
1. Internet is off
2. User tries to reload or scroll down to get more questions or any other data
3. Show the snack bar that the internet is off and stop the fetching of data.

**Comment by BismeetSingh** [comment]
Okay, then the change needs to be made in every fragment right?

**Comment by cdhiraj40** [comment]
> Okay, then the change needs to be made in every fragment right?

For this PR you can make changes just for this fragment, but you can surely create an issue containing links to different fragments where this can be implemented!
Someone can pick any one fragment and implement it.

**Comment by cdhiraj40** [comment]
Also @BismeetSingh do update the branch with latest code.

**Comment by BismeetSingh** [comment]
I am trying to use the connectivity manager callback which is asynchronous and having some issues with it, as its not synchronous.

**Comment by BismeetSingh** [comment]
https://user-images.githubusercontent.com/13601266/197372219-fd64ac55-86d9-4f9b-bba0-981c37e3232a.mp4

**Review by cdhiraj40 — APPROVED** [review]
Hey, @BismeetSingh this looks good for now 🚀 Thanks for your contributions 🎉

**Pull request merged**
